name: servant-swagger-ui
version: 0.1.0.2.1.4
synopsis: Servant swagger ui
description: Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/servant-swagger-ui
category: Web
tested-with: GHC==7.10.3
extra-source-files:
- README.md
- index.html.tmpl
- swagger-dist-2.1.4/**/*

ghc-options: -Wall

dependencies:
  - base              >=4.7      && <4.9
  - blaze-markup      >=0.7.0.3  && <0.8
  - bytestring        >=0.10.4.0 && <0.11
  - directory         >=1.2.2.0  && <1.3
  - file-embed        >=0.0.9    && <0.1
  - filepath          >=1.4.0.0  && <1.5
  - http-media        >=0.6.2    && <0.7
  - servant           >=0.4.4.5  && <0.5
  - servant-blaze     >=0.4.4.5  && <0.5
  - servant-server    >=0.4.4.5  && <0.5
  - servant-swagger   >=0.1.2    && <0.2
  - swagger2          >=1.2.1    && <1.3
  - template-haskell  >=2.10     && <2.11
  - text              >=1.2.2    && <1.3
  - wai-app-static   >=3.0.1.1   && <3.2

library:
  source-dirs: src

tests:
  example:
    main: Main.hs
    source-dirs: example
    dependencies:
      - servant-swagger-ui
      - servant-server >=0.4.4.5  && <0.5
      - aeson          >=0.9      && <0.11
      - base-compat    >=0.6.0    && <0.10
      - lens           >=4.13     && <4.14
      - wai            >=3.0.3.0  && <3.3
      - warp           >=3.0.13.1 && <3.3
